config/routes.rb
Taylor::Application.routes.draw do

  root :to => 'home#index'
  get '/team' => 'home#team'

  get '/contact' => 'home#contact'
  post '/contact/submit' => 'home#send_contact_email'

  post 'search' => 'venues#search'
  match '/venues' => 'venues#index'
  resources :categories
  resource :items
  match '/items/index' => 'items#index'
  post '/items/create' => 'items#create'

  resources :tags

  resources :venues

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @venues = Venue.all

    @venue_names = []

    @venues.each do |venue|
      @venue_names << venue.name
    end
  end

  def team

  end

  def contact

  end

  def send_contact_email
    TeamMailer.contact_email(params[:name], params[:email], params[:content]).deliver
    flash[:success] = "Thanks for your comment. We'll contact you shortly."
    render :contact
  end

end

app/views/home/_carousel.html.erb
<div class="container">
  <div id="carousel-example-generic" class="carousel slide">

    <!-- Wrapper for slides -->
    <div class="carousel-inner">

      <div class="item active">
        <%= image_tag("shoes.jpg")%>

        <div class="carousel-caption">
          <h3 class='top'>Style profiles</h3><h3 class='middle'> for bars</h3><h3 class='bottom'>around San Francisco</h3>
        </div>
      </div>

      <div class="item">
        <%= image_tag("cafe.jpg")%>
        <div class="carousel-caption">
          <h3 class='item-two-top'>The right clothes</h3><h3 class='item-two-bottom'> for the right places</h3>
        </div>
      </div>
      <div class="item">
         <%= image_tag("styles.jpg", :alt => "900x600px") %>
         <div class="carousel-caption">
          <h3 class='item-three-top'>What to wear</h3> <h3 class='item-three-bottom'>wherever you go</h3>
         </div>
       </div>
    </div>

    <!-- Controls -->
    <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
      <span class="icon-prev"></span>
    </a>
    <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
      <span class="icon-next"></span>
    </a>

    <!-- Indicators -->
    <ol class="carousel-indicators">
      <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
      <li data-target="#carousel-example-generic" data-slide-to="1"></li>
      <li data-target="#carousel-example-generic" data-slide-to="2"></li>
    </ol>



  </div>
</div>

app/views/home/contact.html.erb
   <section>
      <div class="contactform">
    <h1> We want to hear from you!</h1>
<%= form_tag contact_submit_path do %>
  <p>
   <%= label_tag :name %>
   <br>
   <%= text_field_tag :name %>
  </p>
  <br>
  <p>
   <%= label_tag :email %>
   <br>
   <%= email_field_tag :email %>
   <br>
  </p>
  <p>
  <%= label_tag :content, "Comment" %>
  <br>
  <%= text_area_tag :content %>
  </p>
  <p><%= submit_tag "Submit" %></p>
 <% end %>
</div>
</section>

app/views/home/index.html.erb
<section class="heroes-container-1">
  <div class="heroes-1">

    <%= render 'carousel' %>
    <!-- search bar is in carousel partial -->

  </div>
</section>

<div class="search-container">

  <div class="search">
    <div class='search-bar'>
      <%= form_tag(controller: "venues", action: "search", method: "get") do %>
      <%= text_field_tag(:venue, nil, placeholder: 'Where do you want to go?') %>
      <%= radio_button_tag(:gender, "m", true) %><%= label_tag(:gender_m, "Man") %>
      <%= radio_button_tag(:gender, "f") %><%= label_tag(:gender_f, "Woman") %>
      <br/>
    </div>
      <%= submit_tag("SEARCH") %>
      <% end %>
    </div>
  </div>

</div>


<section class="heroes-container-2">
  <div class="heroes-2">
    <div class="blurb-2">
      <h1>Tailored inspiration</h1>
      <h3>/ Intelligent algorithm that takes every factor into account: venue location, crowd and even weather. We pay attention so you don't have to /</h3>
    </div>
    <div class="image-2">
      <%= image_tag("shirts.png", :alt => :shirts) %>
    </div>
  </div>
</section>

<section class="heroes-container-3">
  <div class="heroes-3">

    <div class="image-3">
      <%= image_tag("mac.png", :alt => :shirts) %>
    </div>

    <div class="blurb-3">
      <h1>Powered by Zappos</h1>
      <h3>/ Thousands of clothing items from Zappos curated under one view /</h3>
    <div>
  </div>
</section>

<section class="heroes-container-4">
  <div class="heroes-4">
    <div class="blurb-4">
      <h1>Tick Tock Tag</h1>
      <h3>/ Are you a fashionista? Tag your outfits to your favorite venues /</h3>
    </div>
    <div class="image-4">
      <%= image_tag("tags.png")%>
    </div>

  </div>
</section>



<script src="assets/bootstrap.js"></script>

<%= javascript_tag do %>
    var venueNames = <%= @venue_names.to_json.html_safe %>
<% end %>

<script>
  $("#venue").autocomplete({
    source: venueNames
  });
</script>

app/views/home/team.html.erb
<section class="heroes-container">
  <div class="heroes">
    Working Process
  </div>
</section>

<section class="heroes-container">
  <div class="heroes">
    <div class="team-member">
      A
    </div>
    <div class="team-member">
      B
    </div>
    <div class="team-member">
      C
    </div>
    <div class="team-member">
      D
    </div>
  </div>
</section>