config/routes.rb
Taylor::Application.routes.draw do

  root :to => 'home#index'
  get '/team' => 'home#team'

  get '/contact' => 'home#contact'
  post '/contact/submit' => 'home#send_contact_email'

  post 'search' => 'venues#search'
  match '/venues' => 'venues#index'
  resources :categories
  resource :items
  match '/items/index' => 'items#index'
  post '/items/create' => 'items#create'

  resources :tags

  resources :venues

end

app/models/venue.rb
class Venue < ActiveRecord::Base
  include Yelp::V2::Business::Request
  include Yelp::V2::Search::Request
  attr_accessible :name, :address_1, :address_2, :zip, :city, :state, :rating, :img_url, :biz_url, :YID, :snippet_text, :mobile_url, :neighborhood_name, :closed
  has_many :taggings, :as => :taggable, :dependent => :destroy
  has_many :tags, :through => :taggings

  belongs_to :neighborhood

  validates_presence_of :name


end

app/controllers/venues_controller.rb
class VenuesController < ApplicationController
  include VenuesHelper

  def index
  end

  def search

    @title = params[:venue]
    @gender = params[:gender]
    @clothing_category = ['Tops','Bottoms', 'Jackets and Coats', 'Suits', 'Dresses', 'Jumpsuits and Rompers'].sample #need to add more, also with logic that contains gender
    @shoes_category = []
    @accessories_category = []

    @weather = wunderweather

    if @venue = Venue.find_by_name(@title) #check w ian
      render 'index'
    else
      redirect_to '/'
    end

  end

end

app/helpers/venues_helper.rb
module VenuesHelper

require 'open-uri'
require 'json'

  def wunderweather

    url = 'http://api.wunderground.com/api/749186801b144fe7/hourly/q/CA/San_Francisco.json'
    result = JSON.parse(open(url).read)
    return result

  end

end

app/views/venues/_show.html.erb
<div class="show">

  <div class="clothes">
    <h3>Try these clothes</h3>

    <div class="items-container">

      <div class="items-block">
        <div class="items">
          <a href="image_url"><img src="http://imagesecaw.ctscdn.com/image/263/375/d42652d7-2472-401c-85f7-f7c792dee96d.jpg" /></a>
          <div class="likes">
            <button>Like</button>
          </div>
        </div>
      </div>

      <div class="items-block">
        <div class="items">
          <a href="image_url"><img src="http://imagesecaw.ctscdn.com/image/263/375/2cd3213a-cc49-43d9-92e5-11322931be8c.jpg" /></a>
          <div class="likes">
            <button>Like</button>
          </div>
        </div>
      </div>

      <div class="items-block">
        <div class="items">
          <a href="image_url"><img src="http://imagesecaw.ctscdn.com/image/263/375/65ca1960-82e2-4fb7-ad06-5200b499da7a.jpg" /></a>

          <div class="likes">
            <button>Like</button>
          </div>
        </div>
      </div>
    </div>

    <div class="more">

      <a href="#"><span class="entypo-right-open-big"></span></a></br>
      <div class="add-tags"><%= link_to '+', items_index_path(:gender => @gender, :category => @clothing_category, :tag => @venue.tags ) %></div>

    </div>

  </div>


  <div class="shoes">
    <h3>That goes with those shoes</h3>
  </div>

  <div class="accessories">
    <h3>...and spiced up by those accessories</h3>
  </div>

</div>

app/views/venues/_tab.html.erb
<div class="venue-tab">

  <div class="details">

    <div>
      <img src="<%= @venue.img_url %>" />
    </div>

    <div>
      <ul>
        <li><p><%= @venue.address_1 %>, <%= @venue.address_2 %></p></li>
        <li><p><%= @venue.neighborhood_name %></p></li>
        <li><p><%= @venue.rating.inspect %></p></li>
    </div>

    <div>
      <p>/ <%=@venue.snippet_text %> /</p>
    </div>

  </div>

  <div class="weather">
    <img src="<%= @weather['hourly_forecast'][1]['icon_url'] %>" />

  </div>

  <div class="tags">


    <div>
      <ul>
        <% @venue.tags.each do |tag| %>
        <li>#<%= tag['name'] %>   </li>
        <% end %>
      </ul>
    </div>

  </div>

</div>

app/views/venues/index.html.erb
<div class="fixed-top">
  <div class="venue-menu-container">

    <div class="venue-menu">
      <h3><%= @venue.name.upcase %></h3>
      <ul>
        <li><a href="#">Details</a></li>
        <li><a href="#">Weather</a></li>
        <li><a href="#">Tags</a></li>
      </ul>
    </div>

  </div>

  <%= render 'tab' %>

</div>

<div class="alternate-fixed-top">
  <div class="alternate-venue-menu-container">
    <div class="alternate-venue-menu">
      <h3>What would you would wear to <%= @venue.name.titleize %>?</h3>
      <ul>
        <li><a href="#" id='confirm'><span class="entypo-check"></span></a></li>
        <li><a href="#", id='back-home'><span class="entypo-cancel"></span></a></li>
      </ul>
    </div>
  </div>
</div>

<div class="venue-content">
  <section class="venue-items-container">
    <%= render 'show' %>

    <div class="add">
      <%= image_tag("loading.gif", :class => 'loading')%>
    </div>
  </section>
</div>


<script>
// fixed header on scroll

  function fixDiv() {
    var $cache = $('.fixed-top');

    if ($(window).scrollTop() > 120) {
      $cache.css({'position': 'fixed', 'top': '0'});
      $('.venue-content').css('margin-top','50px');
    } else {
      $cache.css({'position': 'relative', 'top': 'auto'});
      $('.venue-content').css('margin-top','0');
    }
  }

  $(window).scroll(fixDiv);

  fixDiv();
</script>

<script>
// display tab modal

$('.venue-menu ul li:nth-child(1)').click(function(event){
  event.preventDefault();
  $('.venue-tab').slideDown('slow');
  $('.weather').css('display', 'none');
  $('.tags').css('display', 'none');
  $('.details').fadeIn();

  $('.venue-menu ul li:nth-child(1)').css('background', 'rgba(250,250,250,1)');
  $('.venue-menu ul li:nth-child(2)').css('background', 'transparent');
  $('.venue-menu ul li:nth-child(3)').css('background', 'transparent');

});

$('.venue-menu ul li:nth-child(2)').click(function(event){
  event.preventDefault();
  $('.venue-tab').slideDown('slow');
  $('.details').css('display', 'none');
  $('.tags').css('display', 'none');
  $('.weather').fadeIn();

  $('.venue-menu ul li:nth-child(1)').css('background', 'transparent');
  $('.venue-menu ul li:nth-child(2)').css('background', 'rgba(250,250,250,1)');
  $('.venue-menu ul li:nth-child(3)').css('background', 'transparent');

});

$('.venue-menu ul li:nth-child(3)').click(function(event){
  event.preventDefault();
  $('.venue-tab').slideDown('slow');
  $('.details').css('display', 'none');
  $('.weather').css('display', 'none');
  $('.tags').fadeIn();

  $('.venue-menu ul li:nth-child(1)').css('background', 'transparent');
  $('.venue-menu ul li:nth-child(2)').css('background', 'transparent');
  $('.venue-menu ul li:nth-child(3)').css('background', 'rgba(250,250,250,1)');

});

$('.venue-tab').click(function(event){
  event.preventDefault();
  $('.venue-tab').slideUp('slow');

  $('.venue-menu ul li:nth-child(1)').css('background', 'transparent');
  $('.venue-menu ul li:nth-child(2)').css('background', 'transparent');
  $('.venue-menu ul li:nth-child(3)').css('background', 'transparent');
});

</script>

<script>
// display add modal

// PREVIOUS JQ
// change header when .add div is displayed
// display and remove .add div (user clothing tagging)
$(document).ready(function(){
  $(".add-tags").click(function(event){
    event.preventDefault();

    var select = $(this).children();

    $(".fixed-top").slideUp('fast', function() {

      $(".alternate-fixed-top").slideDown('fast', function() {
        $(".add").slideDown(800);
        $('.loading').css('display','block');

        $.ajax({

          url: select.attr("href"),
          success: function(data) {
            $('.add').append(data);
            $('.loading').css('display','none');
          }
        })

      });
    });
  });

  $('#back-home').click(function(){
    event.preventDefault();
    $('.add').fadeOut(500);
    $(".alternate-fixed-top").fadeOut(100);
    $(".fixed-top").fadeIn(500);
    $("html, body").animate({ scrollTop: 0 }, 400);
      return false;

  });
});

</script>

<script>
// previous JQ
// fix .add div
function fixTabDiv() {
    var $tabCache = $('.alternate-fixed-top');

      if ($(window).scrollTop() > 140) {
        $tabCache.css({'position': 'fixed', 'top': '0'});
        $('.venue-content').css('margin-top','50px');
      } else {
        $tabCache.css({'position': 'relative', 'top': 'auto'});
        $('.venue-content').css('margin-top','0');
      }

  }

$(window).scroll(fixTabDiv);
fixTabDiv();

</script>